
# setting the universe to vanilla will require --container argument
#universe = vanilla
# comment out the line above and uncomment the line below to run the scripts
# inside the container. Also, remove the --container argument
# from arguments
container_image = file:///staging/USERNAME/af3complex.sif

executable = inference_pipeline.complex.sh

log = ../logs/inference_pipeline.complex.log
output = ../logs/inference_pipeline.complex.$(Cluster)_$(Process).out
error  = ../logs/inference_pipeline.complex.$(Cluster)_$(Process).err

initialdir = $(directory)
# transfer all files in the inference_inputs directory
transfer_input_files = inference_inputs/

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# We need this to transfer the model weights to the execute node
Requirements = (Target.HasCHTCStaging == true) && (has_avx == true) && (CUDAGlobalMemoryMb > 16000)

request_memory = 32GB
# need space for the container (3GB) as well
request_disk = 5GB
request_cpus = 4
request_gpus = 1

# we should be able to run short jobs on CUDA_CAPABILITY=7.x but need
# other environment variables and options to be set. This is done automatically
# in inference_pipeline.complex.sh
gpus_minimum_capability = 7.0

# need more GPU memory for larger jobs

# short jobs 4-6 hours so it is okay to use is_resumable
+GPUJobLength = "short"
+WantGPULab = true
+is_resumable = true

#arguments = --container alphafold3.sif --model_param_file /staging/dcosta2/af3/weights/af3.bin --work_dir_ext $(Cluster)_$(Process)
arguments = --model_param_file /staging/USERNAME/af3/weights/af3.bin.zst --work_dir_ext $(Cluster)_$(Process)

queue directory matching job*

