container_image = file:///staging/s/saodonnell/af3complex.sif

executable = dagman.1-PAIRING.msa_pairing.sh

arguments = $(probe) $(dataset)

log = logs/dagman.1-PAIRING.msa_pairing.log
output = logs/dagman.1-PAIRING.msa_pairing.$(Cluster)_$(Process).out
error = logs/dagman.1-PAIRING.msa_pairing.$(Cluster)_$(Process).err

initialdir = $(directory)

# transfer what the job needs
transfer_input_files = dagman.1-PAIRING.msa_pairing.py,file:///staging/s/saodonnell/af3_proteomes/$(dataset)/proteome_msa.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# send generated folders back
transfer_output_files = msa_pairing_output.tar.gz

Requirements = (Target.HasCHTCStaging == true) && (has_avx == true)

request_memory = 16GB
request_disk = 200GB
request_cpus = 2

queue